---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint

platforms:
  - name: tomcat
    groups:
      - tomcat
    image: ${DOCKER_IMAGE_BASE:-debian:jessie-slim}
    privileged: True
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: tomcat
verifier:
  name: goss
  lint:
    name: yamllint
