---
- name: Converge
  hosts: tomcat
  pre_tasks:
    - name: Tomcat | Installing required dependencies
      apt:
        pkg: ['net-tools']
        state: present
      when:
        - ansible_os_family == 'Debian'
  roles:
    - tomcat-role
