---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Tomcat | Installing required dependencies, for Debian and Ubuntu
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - net-tools
        - apt-transport-https
      when:
        - ansible_os_family == 'Debian'
  roles:
    - tomcat-role
